### ISSUE TITLE
Some enhancements that would make your app to the next level

### ISSUE THREAD

**Issue by DonKirkham** [LanceMcCarthy/MvpApi#211] opened 2022-03-02 22:38 UTC
First time using the app and I really like the clone feature since it makes it easier to add multiple events with similar metadata.

What would be nice is to make settings "stick."  For example, if I set a Group By or one of the filter options, everything is reset if I navigate off the screen and come back.

For date filter, offer option to just show the current contribution period (using the default or overide date, if set). Make it the default filter for Date.

I added a new item to the upload queue and then navigated back to the Home screen to look at something. WHen I came back, my queue was empty. Please make it persist until uploaded or manually cleared.

I was having the display issue for small batches, but the update fixed it.  It would be nice to have that fixed for the default batch size since it resets everytime you start the app.

Again, I hope I am not coming across as critical. It's the best app I have found for this. I have not used the export/import option yet, but can see that being in my future as excel would be so much faster to enter and bulk upload. Thanks for doing this.

**Comment by LanceMcCarthy** [comment] 2022-03-02 23:33
Hi Don, thank you for the feedback, it is very useful. Let me get to some of the items:

> I was having the display issue for small batches, but the update fixed it. It would be nice to have that fixed for the default batch size since it resets every time you start the app.

About the Batch Size setting, that should persist. Every time you change the value, it gets saved to the LocalStorage and any time the value is fetched, it comes from that same stored setting ([here's the code if you're curious](https://github.com/LanceMcCarthy/MvpApi/blob/25785de56aa0ddfcfda45dc4310158b64ba26f11/src/MvpApi.Uwp/ViewModels/HomeViewModel.cs#L84-L111)). 

Can you relaunch the app and tell me if it kept your last batch size setting? 

> What would be nice is to make settings "stick." For example, if I set a Group By or one of the filter options, everything is reset if I navigate off the screen and come back.
> I added a new item to the upload queue and then navigated back to the Home screen to look at something. When I came back, my queue was empty. Please make it persist until uploaded or manually cleared.

This is great feedback and achievable in just a day or two of working on it.  I have created the following Feature Requests so you can track them and know when an update is incoming with those features:

#212 
#214

> For date filter, offer option to just show the current contribution period (using the default or overide date, if set). Make it the default filter for Date.

This is the intention, thats why there is a static class with code that calculates the current award period (because it is the only time you can upload any changes to the API. Prior year contributions are not editable, or deleted.

I will investigate this and see why the behavior is not working as intended. I create a new bug report to track this #213

> Again, I hope I am not coming across as critical. It's the best app I have found for this. 

You are no coming across as critical. I need this type of feedback to keep fresh eyes on the user experience. I've been working on this app for many years. Things change and I need to evolve.

> I have not used the export/import option yet, but can see that being in my future as excel would be so much faster to enter and bulk upload. Thanks for doing this.


The Excel import is still very early, this is because the validation is **very** complicated. I have a prototype excel document for folks to use as their starting point, I used the raw API data model structure as a data sources for the validation in this starting Excel doc, but I have not had the chance to try it for importing yet (I'm still knocking down some other issues before I come back to it)

**Comment by LanceMcCarthy** [comment] 2022-06-21 18:18
Closed - The MVP API is no longer available, I am closing all Issues and archiving this repository.

**Closed by LanceMcCarthy** 2022-06-21 18:18 UTC
