### ISSUE TITLE
Unexpected Error on first time start up.

### ISSUE THREAD

**Issue by DavidEPatrick** [LanceMcCarthy/MvpApi#124] opened 2021-02-04 18:11 UTC
![MVPComp-StartUpError](https://user-images.githubusercontent.com/9697582/106936408-87b37e80-66ea-11eb-8195-fd770880fc12.png)

Error gives me the chance to send email to 

awesome.apps@outlook.com

MVP Companion Error

----------------------------------------------------------------- 
Source: <unknown> 
Date Time: 2/4/2021 1:06:48 PM 
----------------------------------------------------------------- 
Method: Object reference not se

**Comment by LanceMcCarthy** [comment] 2021-02-04 18:35
Thanks for opening case. Yes, please send the stacktrace to the email (the button will handle everything for you)

**Comment by halhos** [comment] 2021-02-26 23:04
I have exactly the same issue, happy to help.

**Comment by LanceMcCarthy** [comment] 2021-03-16 22:15
I've found some evidence this can also occur with the new merged category GUIDs, I am using [Dimitar's profile](https://mvp.microsoft.com/en-us/PublicProfile/5002880) as a proven repro set of categories (his always crashes), if yours match any of his, let me know which ones and I'll prioritize those contribution category first.

**Comment by HalHostetler** [comment] 2021-03-17 00:33
First and foremost, Office365!  Others are Azure Compute, Azure Storage, Identity and Access, Microsoft Teams, Service Bus, Azure Security...  I'm guessing if his passes, mine will too.

Hal
--
Hal Hostetler, CPBE
Broadcast Engineer/I.T. Pro
MS MVP-Outlook - WA7BGX
www.rolandschorr.com<http://www.rolandschorr.com/>

**Comment by LanceMcCarthy** [comment] 2021-03-22 22:16
UPDATE I have been testing these categories and have not yet seen a locally reproducible exception form them. However, I did some improvements to parsing that reduces the opportunity for an exception to happen. 

I'll be pushing a custom build, Are you all willing to try a beta? 

Super easy to install, just click a "get the app" button and it will automatically install. Once you install it, it will automatically check for updates every 6 hours, you don't have to do anything,

As an example of what the install page works like, take a look at my Media File Manager app. https://dvlup.blob.core.windows.net/general-app-files/Installers/MediaFileManager/index.html

**Comment by HalHostetler** [comment] 2021-03-22 22:43
Absolutely willing!!  As soon as I get a link, I'll install the update!!

Hal
--
Hal Hostetler, CPBE
Broadcast Engineer/I.T. Pro
MS MVP-Outlook - WA7BGX
www.rolandschorr.com<http://www.rolandschorr.com/>

**Comment by LanceMcCarthy** [comment] 2021-03-23 00:05
Ready. This version will be a little slower loading the initial profile info, but that is intentional. It will be faster in the final verison.

### Install

1. Uninstall the Microsoft Store version of the app
2. Go to this link [MVP Companion Side-load Page](https://dvlup.blob.core.windows.net/general-app-files/Installers/MvpCompanion/index.html) 
3. Click "Get the app"
4. It will download an `appinstaller` file that will begin the install (once you approve it). 

#### Notes

- This installer is 100% trusted and is from Microsoft themselves, I have signed the code with my own DigiCert code signing certificate.
- This version supports ARM64, ARM, x86 and x64.  The installer will automatically pick the right one for the device you run it on.


### Test

When you run it and sign in, pay attention to when it initially loads everything. I need to know if it crashes during the "signing in...", "getting profile info...", "downloading profile photo.." or "loading contributions". 

I'll be working on a new update tomorrow that will actually gather better details (the complete exception) and create a log file that will attach to the crash report email automatically for you. I want it to be as effortless as possible for you.

Thanks!

**Comment by LanceMcCarthy** [comment] 2021-03-23 00:16
Sorry for the double reply, it looks like something went wrong with the relative URL in the appinstaller. Just expand the little down arrow and download and the appx instead

1 Click here
![image](https://user-images.githubusercontent.com/3520532/112073938-7106a100-8b4b-11eb-8e1e-4f6ed3ec0bd7.png)

2 Open the downloaded file to install

**Comment by HalHostetler** [comment] 2021-03-23 06:47
Per the store version, no issues signing in or loading profile, it crashes Loading Contributions.

Hal
--
Hal Hostetler, CPBE
Broadcast Engineer/I.T. Pro
MS MVP-Outlook - WA7BGX
www.rolandschorr.com<http://www.rolandschorr.com/>

**Comment by HalHostetler** [comment] 2021-03-23 06:56
[Graphical user interface, text  Description automatically generated]

Hal
--
Hal Hostetler, CPBE
Broadcast Engineer/I.T. Pro
MS MVP-Outlook - WA7BGX
www.rolandschorr.com<http://www.rolandschorr.com/>

**Comment by LanceMcCarthy** [comment] 2021-03-23 16:54
@HalHostetler @DavidEPatrick 

There should be a crash log file stored, even though the 256 character limit clipped the email message. Can you please send it to me at awesome.apps@outlook.com

1. Open the following folder on your PC 
`C:\Users\[your-user-name]\AppData\Local\Packages\61469LanceLotSoftware.MVPCompanion_m6f3850p49bnt\LocalState`
2. Grab the latest file with named `MVPCompanion_ErrorLog_yyyyMMdd.log`

Note: there may be device info in there, so I recommend you do not post it here.

**Comment by LanceMcCarthy** [comment] 2021-03-23 18:29
@HalHostetler You've replied to the public GitHub thread notification email. The attachment doesnt get posted to the GitHub thread.

Can you please send it to me directly at awesome.apps@outlook.com  ? Thanks!

**Comment by HalHostetler** [comment] 2021-03-23 18:33
Sent.

Hal
--
Hal Hostetler, CPBE
Broadcast Engineer/I.T. Pro
MS MVP-Outlook - WA7BGX
www.rolandschorr.com<http://www.rolandschorr.com/>

**Comment by LanceMcCarthy** [comment] 2022-02-07 16:32
Good news folks, I have released a new version of the app that uses the API's new features that allows the app to pull only contributions for the Current award cycle, Historical contributions and All.

This means that if you had an error before when it took  a long time to load everything, this new release should fix it.

## Installation Instructions
I have the preview version hosted on Azure so that you can try it before it goes live in the Store. Try these steps:

1. Uninstall the current version of the app from your machine
2. Go to [https://dvlup.blob.core.windows.net/general-app-files/MVP%20Companion/Distribution/index.html](https://dvlup.blob.core.windows.net/general-app-files/MVP%20Companion/Distribution/index.html)
3. Expand the “Additional Links” section (don’t click the “get the app” button because Microsoft disabled the functionality in Windows 10)
4. Click the “App Installer File” link (that will download a file named “Mvp.Api.appinstaller”)
5. Run the downloaded appinstaller file (double-click on it) and follow the prompts.

![image](https://user-images.githubusercontent.com/3520532/152829514-37726431-0bf3-4ff8-892c-dedb13528dba.png)

> If you get any errors when trying to install the new version, see the Manual Uninstall steps below

## Manual Uninstall

If you have an issue when installing the new version, you might get an error like 

`App installation failed with error message: Windows cannot install package you have another version still installed`

Follow these steps to manually uninstall the old one.

1. Open a new PowerShell as Administrator, and run the command in step 2
2. Run the following command to locate and delete the old version `Get-AppxPackage 61469LanceLotSoftware.MVPCompanion | Remove-AppxPackage`
3. Go back to Step 4 in the Installation Instructions above.

**Comment by LanceMcCarthy** [comment] 2022-02-15 01:22
Confirmation of fix by multiple testers, closing this issue.

The new version 2022.214 is in certification right now with Microsoft and _should_ be published in about 3 days assuming they don't fail me again for not being able to log into the app (_the MSFT testers are not Microsoft MVPs, so they dont have authorization_).


If you would like to 'side-load' the new version right now, download and open this appinstaller file [2022.214.1 MVP Companion.zip](https://github.com/LanceMcCarthy/MvpApi/files/8065013/2022.214.1.MVP.Companion.zip) (installs fully code-signed, Microsoft-trusted packages).

**Closed by LanceMcCarthy** 2022-02-15 01:22 UTC
Labels: bug, critical
