### ISSUE TITLE
Contribution Uploads Override Date

### ISSUE THREAD

**Issue by adamj7** [LanceMcCarthy/MvpApi#152] opened 2021-07-16 14:06 UTC
The default override date is 2016, and the default submissions deadline override is 2020. It's a pain to keep overriding them because I end up forgetting and losing out all submissions in queue.

Is it possible to dynamically pull dates? 
eg.
If today's date is (CurrentYear,month,day) >= (CurrentYear).04.01
Start: (CurrentYear).04.01
Deadline: (CurrentYear+1).03.31
If today's date is (CurrentYear,month,day) <= (CurrentYear).04.01
Start: (CurrentYear-1).04.01
Deadline: (CurrentYear).03.31

This way, if an override is necessary it's outside of the norm.

**Comment by LanceMcCarthy** [comment] 2021-07-16 15:25
Hi Adam,

I'm working on an update now that will bump up the gloabl Submissions Deadline date.

The MVP Companion app used to use a boundary condition to dynamically set the start and end date based on the current award year (similar to how you've proposed). However, this was an issue when MVPs would try to submit seemingly valid contributions, but the API would reject them. This is just a limitation to the API itself and you could go into the MVP portal and enter the activity. 

Regarding the date overrides,  I thought I had persisted the overrides so that the next time you open the app you don't have to go back into Settings to change it again. I will make sure that it retains whatever you set in there.

**Comment by LanceMcCarthy** [comment] 2021-08-30 22:04
Hi Adam, quick update. I've pushed some changes that include persisting any updates you make to the min and max dates for the contribution year. That way, you do not have to keep changing the setting.

I also added some logic that sets the default to the current MVP year. You can still override it, but it does save you some initial headache if I can't get an update out in time for a new MVP year.

**Comment by adamj7** [comment] 2021-08-31 00:34
Sweet - When is it going to be released? I just checked the Microsoft store for updates and there were none for the MVP Companion. I'm at version 1.9.5.

**Comment by LanceMcCarthy** [comment] 2021-08-31 00:56
It's going through devops build and testing now. I'll let you know when it is live (the version will now be 2021.x.x when the devops builds are done and pushed to Microsoft).

Lance
Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by LanceMcCarthy** [comment] 2021-08-31 16:49
I just pushed a beta release to Microsoft, it can take a few hours to go through

![image](https://user-images.githubusercontent.com/3520532/131536519-f52001eb-c37e-4ad7-b37a-9d1b1e5b734f.png)

If you'd like to be in the beta group, please DM me the Microsoft Account email address you use for the Store 

- on twitter (@lancewmccarthy) 
- or email me at (lance@dvlup.com)

**Comment by LanceMcCarthy** [comment] 2021-09-03 16:08
I pushed the Beta release to Production. It may take a few days to pass certification because of the long weekend. You can check for updates through the Store app to force it to update faster (the new version is 2021.8.31).

Once you get the update, go to the Settings page to see the new auto-configured dates. If you do need to change them in the future, those new values get stored locally so you don't need to do it again.

**Comment by LanceMcCarthy** [comment] 2021-09-03 18:24
Confirmed working after update, closing issue. Overrides are auto-calculated for the current year and any custom overrides are persisted.

**Closed by LanceMcCarthy** 2021-09-03 18:24 UTC
